[id="cache-level-notifications_{context}"]
= Cache-level notifications

Cache-level events occur on a per-cache basis, and by default are only raised on nodes where the events occur.  Note in a distributed cache these events are only raised on the owners of data being affected.  Examples of cache-level events are entries being added, removed, modified, etc.  These events trigger notifications to listeners registered to a specific cache.

Please see the link:{javadocroot}/org/infinispan/notifications/cachelistener/annotation/package-summary.html[Javadocs on the org.infinispan.notifications.cachelistener.annotation package] for a comprehensive list of all cache-level notifications, and their respective method-level annotations.

[NOTE,textlabel="Note",name="note"]
====
Please refer to the link:{javadocroot}/org/infinispan/notifications/cachelistener/annotation/package-summary.html[Javadocs on the org.infinispan.notifications.cachelistener.annotation package] for the list of cache-level notifications available in {brandname}.
====

[id="cluster-listeners_{context}"]
== Cluster Listeners
:context: cluster-listeners

[id="event-filtering-and-conversion_{context}"]
== Event filtering and conversion
:context: event-filtering-and-conversion

[id="initial-state-events_{context}"]
== Initial State Events
:context: initial-state-events

[id="duplicate-events_{context}"]
== Duplicate Events
:context: duplicate-events