[id="installing-brandname-inside-apache-karaf_{context}"]
= Installing {brandname} inside Apache Karaf

The {brandname} jars contain the required OSGi manifest headers and can be used
inside OSGi runtime environments as OSGi bundles. In addition to them you will
need to install the required 3rd party dependencies. You can install them
one by one if you wish but to make things easier for you we are providing Apache
Karaf "features" files (also called "feature repositories") which define all
required dependencies and can be used to install everything in just a few steps.

Installing bundles using "features" requires:

* registering the feature repositories inside Karaf
* installing the features contained in the repositories

You will first need to start the Apache Karaf console:

....
$ cd <APACHE_KARAF_HOME>/bin
$ ./karaf
....

To register a feature repository you need to use the `feature:repo-add` command
(or `features:addUrl` if you are using Apache Karaf 2.3.x) and provide its URL
(Apache Maven URLs are preferred):

....
karaf@root()> feature:repo-add mvn:org.infinispan/infinispan-core/${version}/xml/features
....

Replace `${version}` with the actual version you plan to use.
You can now get the list of available features using:

....
karaf@root()> feature:list | grep infinispan
infinispan-core               | ${version}   |           | infinispan-core-${version} |
....

and install them using:

....
karaf@root()> feature:install infinispan-core/${version}
....

In Apache Karaf the commands are `features:list` and `features:install`.

Alternatively you can just pass the `-i` flag to the `feature:repo-add` command
which will install all the features defined in that repository:

....
karaf@root()> feature:repo-add -i mvn:org.infinispan/infinispan-core/${version}/xml/features
....

This should get you started using {brandname} in library mode. To get additional
functionality just install the corresponding features. For example to use the
RocksDB cachestore install:

....
karaf@root()> feature:repo-add -i mvn:org.infinispan/infinispan-cachestore-rocksdb/${version}/xml/features
....

The URL for the feature repositories is constructed from the Maven artifact coordinates
using the format:

....
mvn:<groupId>/<artifactId>/<version>/xml/features
....

To use {brandname} in client/server mode install the Hot Rod Client feature:

....
karaf@root()> feature:repo-add -i mvn:org.infinispan/infinispan-client-hotrod/${version}/xml/features
....

Currently feature repositories are available for the following artifacts:

* infinispan-commons
* infinispan-core
* infinispan-cachestore-jdbc
* infinispan-cachestore-jpa
* infinispan-cachestore-rocksdb
* infinispan-cachestore-remote
* infinispan-client-hotrod

For more details regarding the commands available inside Apache Karaf please
consult its user manual.