[id="read_{context}"]
= Read-Only Entry View

The function parameters for read-only maps provide the user with a
link:{javadocroot}/org/infinispan/commons/api/functional/EntryView.ReadEntryView.html[read-only entry view]
to interact with the data in the cache, which include these operations:

* link:{javadocroot}/org/infinispan/commons/api/functional/EntryView.ReadEntryView.html#key--[`key()`]
method returns the key for which this function is being executed.
* link:{javadocroot}/org/infinispan/commons/api/functional/EntryView.ReadEntryView.html#find--[`find()`]
returns a Java 8 `Optional` wrapping the value if present,
otherwise it returns an empty optional. Unless the value is guaranteed to
be associated with the key, it's recommended to use `find()` to verify
whether there's a value associated with the key.
* link:{javadocroot}/org/infinispan/commons/api/functional/EntryView.ReadEntryView.html#get--[`get()`]
returns the value associated with the key. If the key has no value
associated with it, calling `get()` throws a `NoSuchElementException`.
`get()` can be considered as a shortcut of `ReadEntryView.find().get()`
which should be used only when the caller has guarantees that there's
definitely a value associated with the key.
* link:{javadocroot}/org/infinispan/commons/api/functional/MetaParam.Lookup.html#findMetaParam-java.lang.Class-[`findMetaParam(Class<T> type)`]
allows metadata parameter information
associated with the cache entry to be looked up, for example: entry
lifespan, last  accessed time...etc.
See link:#meta_parameter[Metadata Parameter Handling] to find out more.