[id="tweaking-the-cluster-configuration-for-your-network_{context}"]
= Tweaking the cluster configuration for your network

Depending on your network setup, you may need to tweak your JGroups set up.
JGroups is configured via an XML file; the file to use can be specified via the GlobalConfiguration:

[source,java]
----
link:code_examples/ConfigExternalJgroupsEmbedded.java[]
----

The link:http://www.jgroups.org/manual/html/index.html[JGroups documentation] provides extensive advice on getting
JGroups working on your network.
If you are new to configuring JGroups, you may get a little lost, so you might want to try tweaking these configuration
parameters:

* Using the system property `-Djgroups.bind_addr=127.0.0.1` causes JGroups to bind only to your loopback interface,
meaning any firewall you may have configured won't get in the way.
Very useful for testing a cluster where all nodes are on one machine.

You can also configure the JGroups configuration to use in {brandname}'s XML configuration:

[source,xml,subs="attributes+",nowrap-option=""]
----
link:config_examples/config_external_jgroups.xml[]
----