ifdef::context[:parent-context: {context}]
[id="consistency-availability-and-partition-tolerance-cap-theorem_{context}"]
= Consistency, Availability and Partition-tolerance (CAP) Theorem
:context: consistency-availability-and-partition-tolerance-cap-theorem

Made famous by link:http://en.wikipedia.org/wiki/Eric_Brewer_(computer_scientist)[Eric Brewer]
at UC Berkeley, this is a theorem of distributed computing that can be
simplified to state that one can only practically build a distributed system
exhibiting any two of the three desirable characteristics of distributed
systems, which are: Consistency, Availability and Partition-tolerance
(abbreviated to CAP).  The theorem effectively stresses on the unreliability of
networks and the effect this unreliability has on predictable behavior and high
availability of dependent systems.

{brandname} has traditionally been biased towards Consistency and Availability,
sacrificing Partition-tolerance.  However, {brandname} does have a
Partition-tolerant, eventually-consistent mode in the pipeline.  This optional
mode of operation will allow users to tune the degree of consistency they
expect from their data, sacrificing partition-tolerance for this added
consistency.

.More resources
* The theorem is well-discussed online, with many good resources to follow up
on, including
link:http://www.julianbrowne.com/article/viewer/brewers-cap-theorem[this document].
* A more recent article by Eric Brewer himself appears on InfoQ
link:http://www.infoq.com/articles/cap-twelve-years-later-how-the-rules-have-changed[a modern analysis of the theorem] .


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]