ifdef::context[:parent-context: {context}]
[id="considerations-with-media-types-and-endpoint-interoperability_{context}"]
= Considerations with Media Types and Endpoint Interoperability
:context: considerations-with-media-types-and-endpoint-interoperability

Configuring {brandname} to store data with a specific media type affects client interoperability.

Although REST clients do support sending and receiving encoded binary data, they are better at handling text formats such as JSON, XML, or plain text.

Memcached text clients can handle String-based keys and byte[] values but cannot negotiate data types with the server. These clients do not offer much flexibility when handling data formats because of the protocol definition.

Java Hot Rod clients are suitable for handling Java objects that represent entities that reside in the cache. Java Hot Rod clients use marshalling operations to serialize and deserialize those objects into byte arrays.

Similarly, non-Java Hot Rod clients, such as the C++, C#, and Javascript clients, are suitable for handling objects in the respective languages. However, non-Java Hot Rod clients can interoperate with Java Hot Rod clients using platform independent data formats.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]