ifdef::context[:parent-context: {context}]
[id="data-grid_{context}"]
= Data grid
:context: data-grid

A data grid is a cluster of (typically commodity) servers, normally residing on
a single local-area network, connected to each other using IP based networking.
Data grids behave as a single resource, exposing the aggregate storage capacity
of all servers in the cluster. Data stored in the grid is usually partitioned,
using a variety of techniques, to balance load across all servers in the cluster
as evenly as possible.  Data is often redundantly stored in the grid to provide
resilience to individual servers in the grid failing i.e. more than one copy is
stored in the grid, transparently to the application.

Data grids typically behave in a peer-to-peer fashion. {brandname}, for example,
makes use of link:http://www.jgroups.org[JGroups] as a group communication
library and is hence biased towards a peer-to-peer design.  Such design allows
{brandname} to exhibit self-healing characteristics, providing service even when
individual servers fail and new nodes are dynamically added to the grid.

{brandname} also makes use of TCP and optionally UDP network protocols, and can
be configured to make use of IP multicast for efficiency if supported by the
network.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]