ifdef::context[:parent-context: {context}]
[id="hot-rod_{context}"]
= Hot Rod
:context: hot-rod

_Hot Rod_ is the name of {brandname}'s custom TCP client/server protocol which
was created in order to overcome the deficiencies of other client/server
protocols such as Memcached. HotRod, as opposed to other protocols, has the
ability of handling failover on an {brandname} server cluster that undergoes a
topology change. To achieve this, the Hot Rod regularly informs the clients of
the cluster topology.

Hot Rod enables clients to do smart routing of requests in partitioned, or
distributed, {brandname} server clusters. This means that Hot Rod clients can
determine the partition in which a key is located and communicate directly with
the server that contains the key. This is made possible by {brandname} servers
sending the cluster topology to clients, and the clients using the same
consistent hash as the servers.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]