ifdef::context[:parent-context: {context}]
[id="hot-rod-admin-tasks_{context}"]
= Hot Rod Admin Tasks
:context: hot-rod-admin-tasks

Admin operations are handled by the Exec operation with a set of well known tasks. Admin tasks are named according to the following rules:

`@@context@name`

All parameters are UTF-8 encoded strings.
Parameters are specific to each task, with the exception of the *flags* parameter which is common to all commands.
The *flags* parameter contains zero or more space-separated values which may affect the behaviour of the command.
The following table lists all currently available flags.

Admin tasks return the result of the operation represented as a JSON string.

.FLAGS
[table,tablepcwidth="100",rowcount="2",header-option="",colcount="2",cols="3,10"]
|===
| permanent | Requests that the command's effect be made permanent into the server's configuration. If the server cannot comply with the request, the entire operation will fail with an error
|===

include::modules/admin-tasks.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]