ifdef::context[:parent-context: {context}]
[id="interceptors_{context}"]
= Interceptors
:context: interceptors

Interceptors are special types of Visitors, which are capable of visiting
commands, but also acts in a chain.  A chain of interceptors all visit the
command, one in turn, until all registered interceptors visit the command.

The class to note is the
link:{javadocroot}/org/infinispan/interceptors/base/CommandInterceptor.html[CommandInterceptor].
This abstract class implements the interceptor pattern, and also implements
Visitor.  {brandname}'s interceptors extend CommandInterceptor, and these add
specific behaviour to specific commands, such as distribution across a network
or writing through to disk.

There is also an experimental asynchronous interceptor which can be used.
The interface used for asynchronous interceptors is
link:{javadocroot}/org/infinispan/interceptors/AsyncInterceptor.html[AsyncInterceptor]
and a base implementation which should be used when a custom implementation is desired
link:{javadocroot}/org/infinispan/interceptors/BaseCustomAsyncInterceptor.html[BaseCustomAsyncInterceptor].
Note this class also implements the `Visitor` interface.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]