ifdef::context[:parent-context: {context}]
[id="marshalling-of-functions_{context}"]
= Marshalling of Functions
:context: marshalling-of-functions

Running functional map in a cluster of nodes involves marshalling and
replication of the operation parameters under certain circumstances.

To be more precise, when write operations are executed in a cluster,
regardless of read-write or write-only operations, all the parameters
to the method and the functions are replicated to other nodes.

There are multiple ways in which a function can be marshalled. The simplest
way, which is also the most costly option in terms of payload size, is
to mark the function as
link:{jdkdocroot}/java/io/Serializable.html[`Serializable`]:

[source,java]
----
link:code_examples/WriteOnlyMapSerializable.java[]
----

{brandname} provides overloads for all functional methods that make lambdas
passed directly to the API serializable by default; the compiler automatically selects
this overload if that's possible. Therefore you can call

[source,java]
----
link:code_examples/WriteOnlyMapWriteFuture.java[]
----

without doing the cast described above.

A more economical way to marshall a function is to provide an {brandname}
link:{javadocroot}/org/infinispan/commons/marshall/Externalizer.html[`Externalizer`] for it:

[source,java]
----
link:code_examples/WriteOnlyMapExternalizer.java[]
----

To help users take advantage of the tiny payloads generated by
`Externalizer`-based functions, the functional API comes with a helper
class called
link:{javadocroot}/org/infinispan/commons/marshall/MarshallableFunctions.html[`org.infinispan.commons.marshall.MarshallableFunctions`]
which provides marshallable functions for some of the most commonly user
functions.

In fact, all the functions required to implement
link:{jdkdocroot}/java/util/concurrent/ConcurrentMap.html[`ConcurrentMap`]
and
link:https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java[`JCache`]
using the functional map API have been defined in
link:{javadocroot}/org/infinispan/commons/marshall/MarshallableFunctions.html[`MarshallableFunctions`].
For example, here is an implementation of JCache's
link:https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L283[`boolean putIfAbsent(K, V)`]
using functional map API which can be run in a cluster:

[source,java]
----
link:code_examples/ReadWriteMapMarshallableFunctions.java[]
----


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]