ifdef::context[:parent-context: {context}]
[id="rest-hot-rod-and-memcached-interoperability-with-custom-java-objects_{context}"]
= REST, Hot Rod, and Memcached Interoperability with Custom Java Objects
:context: rest-hot-rod-and-memcached-interoperability-with-custom-java-objects

If you store entries in the cache as marshalled, custom Java objects, you should configure the cache with the MediaType of the marshalled storage.

Java Hot Rod clients use the JBoss marshalling storage format as the default to store entries in the cache as custom Java objects.

The following example configures the cache to store entries with the `application/x-jboss-marshalling` media type:

[source,xml,subs="attributes+",nowrap-option=""]
----
link:config_examples/encoding_jboss_marshalling.xml[]
----

If you use the Protostream marshaller, configure the MediaType as `application/x-protostream`. For UTF8Marshaller, configure the MediaType as `text/plain`.

[TIP,textlabel="Tip",name="tip"]
====
If only Hot Rod clients interact with the cache, you do not need to configure the MediaType.
====

Because REST clients are most suitable for handling text formats, you should use primitives such as `java.lang.String` for keys. Otherwise, REST clients must handle keys as `bytes[]` using a supported binary encoding.

REST clients can read values for cache entries in XML or JSON format. However, the classes must be available in the server.

To read and write data from Memcached clients, you must use `java.lang.String` for keys. Values are stored and returned as marshalled objects.

Some Java Memcached clients allow data transformers that marshall and unmarshall objects. You can also configure the Memcached server module to encode responses in different formats, such as 'JSON' which is language neutral. This allows non-Java clients to interact with the data even if the storage format for the cache is Java-specific.

[NOTE,textlabel="Note",name="note"]
====
Storing Java objects in the cache requires you to deploy entity classes to {ProductName}. See link:#entities_deploy[Deploying Entity Classes].
====

[table,tablepcwidth="100",rowcount="7",header-option="",colcount="2",cols="2*"]
|===
| REST clients | Yes
| Java Hot Rod clients | Yes
| Memcached clients | Yes
| Non-Java Hot Rod clients | No
| Querying and Indexing | No
| Custom Java objects | Yes
|===


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]