ifdef::context[:parent-context: {context}]
[id="the-cache-interface_{context}"]
= The Cache interface
:context: the-cache-interface

{brandname}'s Caches are manipulated through the link:{javadocroot}/org/infinispan/Cache.html[Cache] interface.

A Cache exposes simple methods for adding, retrieving and removing entries, including atomic mechanisms exposed by the JDK's ConcurrentMap interface.  Based on the cache mode used, invoking these methods will trigger a number of things to happen, potentially even including replicating an entry to a remote node or looking up an entry from a remote node, or potentially a cache store.

[NOTE,textlabel="Note",name="note"]
====
For simple usage, using the Cache API should be no different from using the JDK Map API, and hence migrating from simple in-memory caches based on a Map to {brandname}'s Cache should be trivial.
====

include::modules/performance-concerns-of-certain-map-methods.adoc[leveloffset=+1]

include::modules/mortal-and-immortal-data.adoc[leveloffset=+1]

include::modules/putforexternalread-operation.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]