ifdef::context[:parent-context: {context}]
[id="the-countermanager-interface_{context}"]
= The <code>CounterManager</code> interface.
:context: the-countermanager-interface

The `CounterManager` interface is the entry point to define, retrieve and remove a counter.
It automatically listen to the creation of `EmbeddedCacheManager` and proceeds with the registration  of an
instance of it per `EmbeddedCacheManager`.
It starts the caches needed to store the counter state and configures the default counters.

Retrieving the `CounterManager` is as simple as invoke the
`EmbeddedCounterManagerFactory.asCounterManager(EmbeddedCacheManager)`
as shown in the example below:

[source,java]
----
link:code_examples/CounterManagerEmbedded.java[]
----

For Hot Rod client, the `CounterManager` is registered in the RemoteCacheManager and it can be retrieved like:

[source,java]
----
link:code_examples/CounterManagerRemote.java[]
----

include::modules/remove-a-counter-via-countermanager.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]